In [1]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import yfinance as yf
import pandas as pd

In [3]:
# Mendapatkan data saham Bank central Asia (simbol: BBCA.JK) dari 1 Januari 2023 hingga 14 Juni 2023
data = yf.download('BBCA.JK', start='2023-01-01', end='2023-06-14')

# Menyimpan data ke file CSV
data.to_csv('data_saham.csv', index=False)

# Menampilkan data
print(data)

[*********************100%***********************]  1 of 1 completed
              Open    High     Low   Close    Adj Close     Volume
Date                                                              
2023-01-02  8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
2023-01-03  8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2023-01-04  8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
2023-01-05  8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
2023-01-06  8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
...            ...     ...     ...     ...          ...        ...
2023-06-07  9125.0  9175.0  9075.0  9100.0  9100.000000   87492200
2023-06-08  9075.0  9125.0  9075.0  9125.0  9125.000000   53188400
2023-06-09  9175.0  9175.0  9100.0  9100.0  9100.000000   44632400
2023-06-12  9150.0  9150.0  9100.0  9150.0  9150.000000   38082300
2023-06-13  9175.0  9175.0  9100.0  9150.0  9150.000000   45552600

[104 rows x 6 columns]


In [4]:
# Membaca file CSV
datasaham = pd.read_csv('data_saham.csv')

# Menampilkan data
print(datasaham)

       Open    High     Low   Close    Adj Close     Volume
0    8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
1    8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2    8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
3    8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
4    8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
..      ...     ...     ...     ...          ...        ...
99   9125.0  9175.0  9075.0  9100.0  9100.000000   87492200
100  9075.0  9125.0  9075.0  9125.0  9125.000000   53188400
101  9175.0  9175.0  9100.0  9100.0  9100.000000   44632400
102  9150.0  9150.0  9100.0  9150.0  9150.000000   38082300
103  9175.0  9175.0  9100.0  9150.0  9150.000000   45552600

[104 rows x 6 columns]


In [5]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
pip install keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import keras
import tensorflow.keras as keras

In [10]:
df = pd.read_csv("data_saham.csv")

In [11]:
target = df['Open']
print(target)

0      8575.0
1      8550.0
2      8525.0
3      8350.0
4      8100.0
        ...  
99     9125.0
100    9075.0
101    9175.0
102    9150.0
103    9175.0
Name: Open, Length: 104, dtype: float64


In [12]:
# Menampilkan beberapa baris pertama data
print(df.head())

# Menampilkan beberapa baris terakhir data
print(df.tail())

     Open    High     Low   Close    Adj Close     Volume
0  8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
1  8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2  8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
3  8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
4  8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
       Open    High     Low   Close  Adj Close    Volume
99   9125.0  9175.0  9075.0  9100.0     9100.0  87492200
100  9075.0  9125.0  9075.0  9125.0     9125.0  53188400
101  9175.0  9175.0  9100.0  9100.0     9100.0  44632400
102  9150.0  9150.0  9100.0  9150.0     9150.0  38082300
103  9175.0  9175.0  9100.0  9150.0     9150.0  45552600


In [13]:
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # Mencari n akhir
    end_ix = i + n_steps
    # Memeriksa urutan terluar dari data
    if end_ix > len(sequence)-1:
      break
    # Menambahkan bagian input dan output
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

# Menentukan Waktu dari data time series
jmlh_X = 4
print('Shapes Target = ',target.shape)
#Split data fitur dan target
X, y = split_sequence(target, jmlh_X)
print('Shapes X = ',X.shape)
print('Shapes Y = ',y.shape)

Shapes Target =  (104,)
Shapes X =  (100, 4)
Shapes Y =  (100,)


In [14]:
newFitur = pd.DataFrame(X, columns=['Xt-'+str(i) for i in range(jmlh_X-1, -1,-1)])
newTarget = pd.DataFrame(y, columns=['Data Prediksi'])

In [15]:
newData = pd.concat([newFitur,newTarget], axis=1)
newData

Xt-3    Xt-2    Xt-1    Xt-0  Data Prediksi
0   8575.0  8550.0  8525.0  8350.0         8100.0
1   8550.0  8525.0  8350.0  8100.0         8325.0
2   8525.0  8350.0  8100.0  8325.0         8400.0
3   8350.0  8100.0  8325.0  8400.0         8050.0
4   8100.0  8325.0  8400.0  8050.0         8150.0
..     ...     ...     ...     ...            ...
95  9200.0  9300.0  9150.0  9050.0         9125.0
96  9300.0  9150.0  9050.0  9125.0         9075.0
97  9150.0  9050.0  9125.0  9075.0         9175.0
98  9050.0  9125.0  9075.0  9175.0         9150.0
99  9125.0  9075.0  9175.0  9150.0         9175.0

[100 rows x 5 columns]

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_norm= scaler.fit_transform(newFitur)
print(X_norm)

[[0.42 0.4  0.38 0.24]
 [0.4  0.38 0.24 0.04]
 [0.38 0.24 0.04 0.22]
 [0.24 0.04 0.22 0.28]
 [0.04 0.22 0.28 0.  ]
 [0.22 0.28 0.   0.08]
 [0.28 0.   0.08 0.08]
 [0.   0.08 0.08 0.  ]
 [0.08 0.08 0.   0.1 ]
 [0.08 0.   0.1  0.12]
 [0.   0.1  0.12 0.24]
 [0.1  0.12 0.24 0.18]
 [0.12 0.24 0.18 0.2 ]
 [0.24 0.18 0.2  0.2 ]
 [0.18 0.2  0.2  0.14]
 [0.2  0.2  0.14 0.52]
 [0.2  0.14 0.52 0.54]
 [0.14 0.52 0.54 0.46]
 [0.52 0.54 0.46 0.42]
 [0.54 0.46 0.42 0.3 ]
 [0.46 0.42 0.3  0.4 ]
 [0.42 0.3  0.4  0.56]
 [0.3  0.4  0.56 0.58]
 [0.4  0.56 0.58 0.62]
 [0.56 0.58 0.62 0.62]
 [0.58 0.62 0.62 0.66]
 [0.62 0.62 0.66 0.66]
 [0.62 0.66 0.66 0.64]
 [0.66 0.66 0.64 0.66]
 [0.66 0.64 0.66 0.62]
 [0.64 0.66 0.62 0.58]
 [0.66 0.62 0.58 0.54]
 [0.62 0.58 0.54 0.58]
 [0.58 0.54 0.58 0.52]
 [0.54 0.58 0.52 0.46]
 [0.58 0.52 0.46 0.58]
 [0.52 0.46 0.58 0.5 ]
 [0.46 0.58 0.5  0.58]
 [0.58 0.5  0.58 0.54]
 [0.5  0.58 0.54 0.44]
 [0.58 0.54 0.44 0.48]
 [0.54 0.44 0.48 0.4 ]
 [0.44 0.48 0.4  0.24]
 [0.48 0.4 

In [17]:
# import knn
from sklearn.neighbors import KNeighborsRegressor
model_knn = KNeighborsRegressor(n_neighbors=11)
features = ['Close', 'High', 'Low', 'Volume']
target = 'Open'

In [28]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [29]:
X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [30]:
# Membuat model KNN
model = KNeighborsRegressor(n_neighbors=11)

In [31]:
# Melatih model dengan seluruh data
X = df[features]
y = df[target]
model.fit(X, y)

KNeighborsRegressor(n_neighbors=11)

In [32]:
# Memasukkan data baru yang ingin diprediksi dari user
new_data = ([[8550, 8600 , 8500 ,10653900 ]])

In [33]:
# Memprediksi harga penutupan (Close) menggunakan data baru
prediction = model.predict(new_data)

# Menampilkan hasil prediksi
print("Prediksi harga open:", prediction[0])

Prediksi harga open: 8745.454545454546


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [36]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# Membuat dan melatih model KNN
model_knn = KNeighborsRegressor(n_neighbors=7)
model_knn.fit(X_train, y_train)

# Melakukan prediksi menggunakan data pengujian
y_pred = model_knn.predict(X_test)

# Menghitung nilai akurasi (contoh menggunakan metrik R2 Score)
accuracy = r2_score(y_test, y_pred)
print("Akurasi model KNN: ", accuracy)


Akurasi model KNN:  0.06579842397731273


In [37]:
# Melakukan prediksi menggunakan data pengujian
y_pred = model_knn.predict(X_test)

In [38]:
def mean_absolute_percentage_error(y_true, y_pred):
    absolute_percentage_error = np.abs((y_true - y_pred) / y_true) * 100
    mean_error = np.mean(absolute_percentage_error)
    return mean_error

mape = mean_absolute_percentage_error(y_test, y_pred)
print("MAPE:", mape)


MAPE: 3.1451382517253785


In [39]:
import pickle

# Simpan model ke dalam file
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(model, file)