#Nama Kelompok

Nama : Arbil Shofiyurrahman (210411100016) 

Nama : Afirza Lucky Pradana (210411100018)

In [1]:
pip list

Package                      Version             
---------------------------- --------------------
absl-py                      1.4.0               
asttokens                    2.2.1               
astunparse                   1.6.3               
attrs                        19.3.0              
Automat                      0.8.0               
Babel                        2.6.0               
backcall                     0.2.0               
blinker                      1.4                 
cachetools                   5.3.1               
certifi                      2019.11.28          
chardet                      3.0.4               
Click                        7.0                 
cloud-init                   22.3.4              
colorama                     0.4.3               
comm                         0.1.3               
command-not-found            0.3                 
configobj                    5.0.6               
constantly                   15.1.0              


In [3]:
pip install scikit-learn


     |████████████████████████████████| 9.8 MB 10.9 MB/s eta 0:00:01
     |████████████████████████████████| 34.5 MB 111.3 MB/s eta 0:00:01
     |████████████████████████████████| 297 kB 92.5 MB/s eta 0:00:01
ERROR: scipy 1.10.1 has requirement numpy<1.27.0,>=1.19.5, but you'll have numpy 1.17.4 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install pandas


     |████████████████████████████████| 12.3 MB 10.1 MB/s eta 0:00:01
     |████████████████████████████████| 502 kB 125.7 MB/s eta 0:00:01
     |████████████████████████████████| 341 kB 77.4 MB/s eta 0:00:01
     |████████████████████████████████| 17.3 MB 87.9 MB/s eta 0:00:01    |████████████████                | 8.7 MB 87.9 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install matplotlib


     |████████████████████████████████| 9.2 MB 9.9 MB/s eta 0:00:01
     |████████████████████████████████| 300 kB 81.3 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 59.3 MB/s eta 0:00:01
     |████████████████████████████████| 1.0 MB 83.8 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [25]:
pip install keras


     |████████████████████████████████| 1.7 MB 10.8 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [50]:
pip install tensorflow


     |████████████████████████████████| 585.9 MB 8.4 kB/s s eta 0:00:01    |███████████████▏                | 278.0 MB 39.5 MB/s eta 0:00:08     |████████████████▋               | 304.2 MB 39.5 MB/s eta 0:00:08     |█████████████████               | 309.6 MB 104.6 MB/s eta 0:00:03    |████████████████████████████▋   | 524.5 MB 116.4 MB/s eta 0:00:01
     |████████████████████████████████| 4.7 MB 102.0 MB/s eta 0:00:01
     |████████████████████████████████| 1.3 MB 92.0 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 2.4 MB 109.4 MB/s eta 0:00:01
     |████████████████████████████████| 5.1 MB 81.3 MB/s eta 0:00:01
     |████████████████████████████████| 304 kB 118.0 MB/s eta 0:00:01
     |████████████████████████████████| 17.1 MB 107.8 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 9.4 MB/s  eta 0:00:01
     |█████████████████████████████

In [2]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import keras
import tensorflow.keras as keras




2023-06-09 08:06:15.577923: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-09 08:06:15.843258: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-09 08:06:15.844631: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-09 08:06:16.937629: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [6]:
df = pd.read_csv("airline-passengers.csv")


In [7]:
import matplotlib.pyplot as plt

In [8]:
target = df['Passengers']
print(target)

0      112
1      118
2      132
3      129
4      121
      ... 
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64


In [9]:
# Menampilkan beberapa baris pertama data
print(df.head())

# Menampilkan beberapa baris terakhir data
print(df.tail())



     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121
       Month  Passengers
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432


In [10]:
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # Mencari n akhir
    end_ix = i + n_steps
    # Memeriksa urutan terluar dari data
    if end_ix > len(sequence)-1:
      break
    # Menambahkan bagian input dan output
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

# Menentukan Waktu dari data time series
jmlh_X = 3
print('Shapes Target = ',target.shape)
#Split data fitur dan target
X, y = split_sequence(target, jmlh_X)
print('Shapes X = ',X.shape)
print('Shapes Y = ',y.shape)

Shapes Target =  (144,)
Shapes X =  (141, 3)
Shapes Y =  (141,)


In [11]:
newFitur = pd.DataFrame(X, columns=['Xt-'+str(i) for i in range(jmlh_X-1, -1,-1)])
newTarget = pd.DataFrame(y, columns=['Data Prediksi'])

In [12]:
newData = pd.concat([newFitur,newTarget], axis=1)
newData

Xt-2  Xt-1  Xt-0  Data Prediksi
0     112   118   132            129
1     118   132   129            121
2     132   129   121            135
3     129   121   135            148
4     121   135   148            148
..    ...   ...   ...            ...
136   472   535   622            606
137   535   622   606            508
138   622   606   508            461
139   606   508   461            390
140   508   461   390            432

[141 rows x 4 columns]

## Normalisasi data Fitur
Menggunakan MinMaxScaler

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_norm= scaler.fit_transform(newFitur)
print(X_norm)

[[0.01544402 0.02702703 0.05405405]
 [0.02702703 0.05405405 0.04826255]
 [0.05405405 0.04826255 0.03281853]
 [0.04826255 0.03281853 0.05984556]
 [0.03281853 0.05984556 0.08494208]
 [0.05984556 0.08494208 0.08494208]
 [0.08494208 0.08494208 0.06177606]
 [0.08494208 0.06177606 0.02895753]
 [0.06177606 0.02895753 0.        ]
 [0.02895753 0.         0.02702703]
 [0.         0.02702703 0.02123552]
 [0.02702703 0.02123552 0.04247104]
 [0.02123552 0.04247104 0.07142857]
 [0.04247104 0.07142857 0.05984556]
 [0.07142857 0.05984556 0.04054054]
 [0.05984556 0.04054054 0.08687259]
 [0.04054054 0.08687259 0.12741313]
 [0.08687259 0.12741313 0.12741313]
 [0.12741313 0.12741313 0.1042471 ]
 [0.12741313 0.1042471  0.05598456]
 [0.1042471  0.05598456 0.01930502]
 [0.05598456 0.01930502 0.06949807]
 [0.01930502 0.06949807 0.07915058]
 [0.06949807 0.07915058 0.08880309]
 [0.07915058 0.08880309 0.14285714]
 [0.08880309 0.14285714 0.11389961]
 [0.14285714 0.11389961 0.13127413]
 [0.11389961 0.13127413 0.14

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.2, random_state=0)

In [32]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()


In [33]:
model_nb.fit(X_train, y_train)
y_pred = model_nb.predict(X_test)


In [34]:
#Hitung MAPE
def mean_absolute_percentage_error(y_true, y_pred):
    absolute_percentage_error = np.abs((y_true - y_pred) / y_true) * 100
    mean_error = np.mean(absolute_percentage_error)
    return mean_error

mape = mean_absolute_percentage_error(y_test, y_pred)
print("MAPE:", mape)


MAPE: 18.209066860384034


In [35]:
#Hitung MAE
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)


MAE: 47.58620689655172


In [36]:
#Hitung SSE
from sklearn.metrics import mean_squared_error

sse = mean_squared_error(y_test, y_pred) * len(y_test)
print("SSE:", sse)


SSE: 108572.0
