In [1]:
pip install yfinance

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "

In [2]:
import yfinance as yf
import pandas as pd

In [3]:
# Mendapatkan data saham Bank central Asia (simbol: BBCA.JK) dari 1 Januari 2023 hingga 14 Juni 2023
data = yf.download('BBCA.JK', start='2023-01-01', end='2023-06-14')

# Menyimpan data ke file CSV
data.to_csv('data_saham.csv', index=False)

# Menampilkan data
print(data)

[*********************100%***********************]  1 of 1 completed
              Open    High     Low   Close    Adj Close     Volume
Date                                                              
2023-01-02  8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
2023-01-03  8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2023-01-04  8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
2023-01-05  8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
2023-01-06  8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
...            ...     ...     ...     ...          ...        ...
2023-06-07  9125.0  9175.0  9075.0  9100.0  9100.000000   87492200
2023-06-08  9075.0  9125.0  9075.0  9125.0  9125.000000   53188400
2023-06-09  9175.0  9175.0  9100.0  9100.0  9100.000000   44632400
2023-06-12  9150.0  9150.0  9100.0  9150.0  9150.000000   38082300
2023-06-13  9175.0  9175.0  9100.0  9150.0  9150.000000   45552600

[104 rows x 6 columns]


berikut adalah arti kolom-kolom yang ditampilkan di bawah :

1. `Open`: Nilai harga saham pada pembukaan perdagangan pada suatu periode tertentu.
2. `High`: Harga tertinggi yang dicapai oleh saham selama periode tersebut.
3. `Low`: Harga terendah yang dicapai oleh saham selama periode tersebut.
4. `Close`: Nilai harga saham pada penutupan perdagangan pada suatu periode tertentu.
5. `Adj Close`: Harga penutupan saham yang telah disesuaikan dengan perubahan harga saham dan faktor-faktor lainnya seperti pembagian saham atau dividen.
6. `Volume`: Jumlah saham yang diperdagangkan pada periode tersebut.

In [4]:
# Membaca file CSV
datasaham = pd.read_csv('data_saham.csv')

# Menampilkan data
print(datasaham)

       Open    High     Low   Close    Adj Close     Volume
0    8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
1    8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2    8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
3    8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
4    8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
..      ...     ...     ...     ...          ...        ...
99   9125.0  9175.0  9075.0  9100.0  9100.000000   87492200
100  9075.0  9125.0  9075.0  9125.0  9125.000000   53188400
101  9175.0  9175.0  9100.0  9100.0  9100.000000   44632400
102  9150.0  9150.0  9100.0  9150.0  9150.000000   38082300
103  9175.0  9175.0  9100.0  9150.0  9150.000000   45552600

[104 rows x 6 columns]


In [5]:
pip install pandas

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "

In [6]:
pip install matplotlib

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "

In [7]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import keras
import tensorflow.keras as keras

2023-06-15 01:21:46.252302: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-15 01:21:46.296740: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-15 01:21:46.297730: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-15 01:21:46.958796: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [8]:
df = pd.read_csv("data_saham.csv")

In [9]:
target = df['Open']
print(target)

0      8575.0
1      8550.0
2      8525.0
3      8350.0
4      8100.0
        ...  
99     9125.0
100    9075.0
101    9175.0
102    9150.0
103    9175.0
Name: Open, Length: 104, dtype: float64


In [10]:
# Menampilkan beberapa baris pertama data
print(df.head())

# Menampilkan beberapa baris terakhir data
print(df.tail())

     Open    High     Low   Close    Adj Close     Volume
0  8575.0  8600.0  8500.0  8550.0  8382.450195   10653900
1  8550.0  8600.0  8525.0  8550.0  8382.450195   27399100
2  8525.0  8575.0  8350.0  8350.0  8186.369141   90918800
3  8350.0  8375.0  8150.0  8250.0  8088.328613  128838500
4  8100.0  8325.0  8100.0  8300.0  8137.349121   69286600
       Open    High     Low   Close  Adj Close    Volume
99   9125.0  9175.0  9075.0  9100.0     9100.0  87492200
100  9075.0  9125.0  9075.0  9125.0     9125.0  53188400
101  9175.0  9175.0  9100.0  9100.0     9100.0  44632400
102  9150.0  9150.0  9100.0  9150.0     9150.0  38082300
103  9175.0  9175.0  9100.0  9150.0     9150.0  45552600


In [11]:
def split_sequence(sequence, n_steps):
  X, y = list(), list()
  for i in range(len(sequence)):
    # Mencari n akhir
    end_ix = i + n_steps
    # Memeriksa urutan terluar dari data
    if end_ix > len(sequence)-1:
      break
    # Menambahkan bagian input dan output
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return np.array(X), np.array(y)

# Menentukan Waktu dari data time series
jmlh_X = 3
print('Shapes Target = ',target.shape)
#Split data fitur dan target
X, y = split_sequence(target, jmlh_X)
print('Shapes X = ',X.shape)
print('Shapes Y = ',y.shape)

Shapes Target =  (104,)
Shapes X =  (101, 3)
Shapes Y =  (101,)


In [12]:
newFitur = pd.DataFrame(X, columns=['Xt-'+str(i) for i in range(jmlh_X-1, -1,-1)])
newTarget = pd.DataFrame(y, columns=['Data Prediksi'])

In [13]:
newData = pd.concat([newFitur,newTarget], axis=1)
newData

Xt-2    Xt-1    Xt-0  Data Prediksi
0    8575.0  8550.0  8525.0         8350.0
1    8550.0  8525.0  8350.0         8100.0
2    8525.0  8350.0  8100.0         8325.0
3    8350.0  8100.0  8325.0         8400.0
4    8100.0  8325.0  8400.0         8050.0
..      ...     ...     ...            ...
96   9300.0  9150.0  9050.0         9125.0
97   9150.0  9050.0  9125.0         9075.0
98   9050.0  9125.0  9075.0         9175.0
99   9125.0  9075.0  9175.0         9150.0
100  9075.0  9175.0  9150.0         9175.0

[101 rows x 4 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_norm= scaler.fit_transform(newFitur)
print(X_norm)

[[0.42 0.4  0.38]
 [0.4  0.38 0.24]
 [0.38 0.24 0.04]
 [0.24 0.04 0.22]
 [0.04 0.22 0.28]
 [0.22 0.28 0.  ]
 [0.28 0.   0.08]
 [0.   0.08 0.08]
 [0.08 0.08 0.  ]
 [0.08 0.   0.1 ]
 [0.   0.1  0.12]
 [0.1  0.12 0.24]
 [0.12 0.24 0.18]
 [0.24 0.18 0.2 ]
 [0.18 0.2  0.2 ]
 [0.2  0.2  0.14]
 [0.2  0.14 0.52]
 [0.14 0.52 0.54]
 [0.52 0.54 0.46]
 [0.54 0.46 0.42]
 [0.46 0.42 0.3 ]
 [0.42 0.3  0.4 ]
 [0.3  0.4  0.56]
 [0.4  0.56 0.58]
 [0.56 0.58 0.62]
 [0.58 0.62 0.62]
 [0.62 0.62 0.66]
 [0.62 0.66 0.66]
 [0.66 0.66 0.64]
 [0.66 0.64 0.66]
 [0.64 0.66 0.62]
 [0.66 0.62 0.58]
 [0.62 0.58 0.54]
 [0.58 0.54 0.58]
 [0.54 0.58 0.52]
 [0.58 0.52 0.46]
 [0.52 0.46 0.58]
 [0.46 0.58 0.5 ]
 [0.58 0.5  0.58]
 [0.5  0.58 0.54]
 [0.58 0.54 0.44]
 [0.54 0.44 0.48]
 [0.44 0.48 0.4 ]
 [0.48 0.4  0.24]
 [0.4  0.24 0.28]
 [0.24 0.28 0.48]
 [0.28 0.48 0.36]
 [0.48 0.36 0.32]
 [0.36 0.32 0.3 ]
 [0.32 0.3  0.32]
 [0.3  0.32 0.2 ]
 [0.32 0.2  0.26]
 [0.2  0.26 0.28]
 [0.26 0.28 0.28]
 [0.28 0.28 0.52]
 [0.28 0.5

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.2, random_state=0)

In [16]:
# import Decision tree
from sklearn.tree import DecisionTreeRegressor
model_decision_tree = DecisionTreeRegressor()

In [17]:
model_decision_tree.fit(X_train, y_train)
y_pred=model_decision_tree.predict(X_test)

In [18]:
def mean_absolute_percentage_error(y_true, y_pred):
    absolute_percentage_error = np.abs((y_true - y_pred) / y_true) * 100
    mean_error = np.mean(absolute_percentage_error)
    return mean_error

mape = mean_absolute_percentage_error(y_test, y_pred)
print("MAPE:", mape)


MAPE: 1.8661293957871143
